language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/dashboard-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn
  clean deploy --settings deploy/settings.xml && exit 0; fi
notifications:
  slack:
    rooms:
      secure: WG4hb5RIO5J/XImHl0VNF/vSPsxpNBVrIlyz3qHR/4C1Yy327b3syfqck7lmHkFqNHVjc1NnxGCBLM2DCs9fZPNBYyJebvFzzJQf/AqHbOXae9ODxByPs4LbWGHbOXiZ2o6fDNa6KozeYPD9M8cK5V5uY8sR+Iqx1AUb4QpdOwSsEnNhsQqAk+RLjbOOUQqtV+q/h+E/mLf6PqUsm17gYwf3+u298dF2B72e8ThHjM11CJNPJaugGwg1zKUQs7UmhGXrUgUJCk/FlhrSoYGIOoDxPU4Z3dPLTs/w7xOCiFi2/q1pgClWnFaQLDQhHC5ckOYAazKd/9yphHVPMXIAJ5BCYyVXwY5MDFnOgyWKgmBz/fDbUsp/4FjwA39HCcsfI+KS55HaL9fsssKxnEphHqRbDg+wcnh7UFl+QKvba7OprlR5yu3EDbs4YQ7SztxSbOEC+iFzm4KOGyfIV0dDBlkFjKtDBjx43IURi1Ma6qStd75alUAUt9Srj/oNzINf7sTCY6TbIJ7jnY1qqHed4LWJmanLXUSR4qoZT6GC1BNmHtBQ2H4miaZ0uq4Vnoqh0hBAUMLRJKkStLhzP87PhnNscdHzXzT0VsgcU1OSCGmwxTX13YU7cqX5xQZ/MHCB//yqme0ezuI5TaQdXaCkp2KYTps9aeMJv+RId945hu4=
    on_success: change
    on_failure: always
env:
  global:
  - secure: TTn+3FRsZ1xd4XxFXNU465UBXekmJ0JS4G2eg/AwYBzEct10OZQ2CBsBXxCKwUZbJxXNIsBO2eo4BwTl0+pEs/3Et0utZuwN9Mn75myQTur+rmIsBZ76nvQHGaCqyKoXG2PsT5XwcEXuDKF+Cnkejp9wBlMXoDVM1rtNAjBufP0VdWx3Z8uaolBwkZ07a/brha4eVgBlIl2NVOg8U9V2VAjxBfEKJwPpNJzX9JSlRg+agHTG6AiFPxvF72QNc47nVAHFaSONCLvFLxMqNO3HAMy7z1jMsRJIhNSKauqLO73UCe5A0fAMNn9o+qxddlsRM3IUygTM+NRhP4NmmvvqxWGDBJPDuFYnnIGiccP3NGteqz/1HIZKdlXbsQw/9uG3Q8prJcPZe/XOR11c/HUd+3lP4q5IDP44jGN3RLXoaRPVpUAy7C8KI686htgqtzYuuETL8kwiH5mdWoACREDs3wpV6Plv4e5t2xVeuJ5Bp2ZKUv0mvzJTW1GjZhnoQbsW6zJjVfCOh2gmfLye5Y7ZQl6iNVf+vIcDpXYkiSDJAWxDo0hvD7ckhOcqhlvBfMeEaT09SemJdq4n2k21c3fILbrDMFRkcBQKXxxgbJuaVo+O83zJZcWBRAK+jdQDKERRlpPKPEGHucM+YAdMb7Yyra/D5Mn5e4qsa5WWaLndb5s=
  - secure: QXrW39sJicW804wouyGCjM91W62uCKi+9sNexQVt1Nx83A3WfNL+ugtAABGyMX8QEdgb+RJhfRF000m4bDPo1EN2RJc254uDH338lwUI82up4bcs04AUwYe/Otvs+uWG6VPg8CHvaeLYzaomxYvmz1OYeuapMcNf5x5N4OXS1+2s8yww7JYPV+P60acalHrsOQ19v/i6bwSd4iBuV2IqcfqZuqVUSMx3GgLuP6rpfyxOnrxIFMQrM7h1+4cs3zEEm6wlmX0Ya+wMwya7F4Vv0QcbVdfIr34O14QQd9/UpFbChUULClI5ubo0AGUJlIjicj3Uf0CVhSZbowSeVBIc0vioKFO/7bZDVvUcDdXZFyf1wN2N7BMl+NKok5690qJd01b1cbfx3AXmzdJ3b6qlEWqxtgK1yKNCsbY6cWdeRXBKHLGRMQyDjJb+TXcJV7yO5rmL6BPeUhbOwavgoCqEoPGokEyl1yM9aKNuHj8Kz1vCtt7MSF6hGwjX9YJScO0NchGxl2skofx/o8SE5/i/lNhMPfvW7WlzeAu6PFSu5XMqDIWpbCmnsOfD3tCLqH2OBrcgQpJtZkbab+faRooHCO/8f1BWXak82KFjpHbjOSuZP98ws+tFeiiX8lE9r2ROwEpExtNBx+9UF+VbwEcV9Sr9F16HH32QBWy8qNyBXxE=
